
export const courseContent = {
  "spoken-english": {
    title: "Spoken English Training",
    subtitle: "Master fluent English communication with confidence",
    icon: "💬",
    image: "/english-learning-classroom.png",
    overview:
      "Our Spoken English Training program is designed to help you communicate fluently and confidently in English. Whether you're a beginner or looking to refine your skills, our expert instructors will guide you through practical exercises, real-world scenarios, and interactive sessions. You'll learn proper pronunciation, grammar, vocabulary, and conversational techniques that will transform your ability to express yourself in English.",
    benefits: [
      "Fluent and confident English communication",
      "Improved pronunciation and accent reduction",
      "Enhanced vocabulary and grammar skills",
      "Practical conversation practice",
      "Increased confidence in professional settings",
      "Better job prospects and career advancement",
    ],
    curriculum: [
      "Fundamentals of English grammar and sentence structure",
      "Pronunciation techniques and accent training",
      "Vocabulary building and contextual usage",
      "Conversational English for daily situations",
      "Business English and professional communication",
      "Presentation skills and public speaking basics",
      "Listening comprehension and audio practice",
      "Mock interviews and real-world scenarios",
    ],
    targetAudience:
      "This course is perfect for students, professionals, and anyone looking to improve their English communication skills. Whether you're preparing for competitive exams, job interviews, or simply want to communicate better in your daily life, this course will help you achieve your goals.",
  },
  "public-speaking": {
    title: "Public Speaking & Personality Development",
    subtitle: "Develop powerful presentation skills and magnetic personality",
    icon: "🎤",
    image: "/confident-speaker-on-stage-presentation.jpg",
    overview:
      "Transform yourself into a confident, charismatic speaker with our comprehensive Public Speaking & Personality Development program. This course combines practical speaking techniques with personality enhancement strategies to help you make a lasting impression. You'll learn to overcome stage fright, structure compelling presentations, engage audiences, and develop the personal magnetism that makes leaders stand out.",
    benefits: [
      "Overcome stage fright and public speaking anxiety",
      "Deliver compelling and engaging presentations",
      "Develop strong body language and presence",
      "Build confidence and self-esteem",
      "Enhance leadership qualities",
      "Create lasting impressions on audiences",
      "Improve career prospects significantly",
      "Develop magnetic personality traits",
    ],
    curriculum: [
      "Understanding public speaking fundamentals",
      "Overcoming fear and building confidence",
      "Presentation structure and content organization",
      "Effective use of visual aids and technology",
      "Body language, gestures, and eye contact",
      "Voice modulation and delivery techniques",
      "Audience engagement and interaction",
      "Handling questions and difficult situations",
      "Personality development and personal branding",
      "Leadership communication skills",
    ],
    targetAudience:
      "This course is ideal for students, professionals, entrepreneurs, and anyone who wants to improve their communication and presentation skills. Whether you're preparing for interviews, business presentations, or simply want to become a more confident speaker, this program will equip you with the tools you need.",
  },
  "soft-skills": {
    title: "Soft Skills & Motivation Training",
    subtitle: "Build essential interpersonal skills and unlock your potential",
    icon: "⭐",
    image: "/team-collaboration-and-teamwork.jpg",
    overview:
      "Soft skills are the foundation of personal and professional success. Our Soft Skills & Motivation Training program focuses on developing the interpersonal abilities that employers value most. From teamwork and leadership to emotional intelligence and time management, you'll gain practical skills that will enhance every aspect of your life and career.",
    benefits: [
      "Enhanced teamwork and collaboration abilities",
      "Improved emotional intelligence",
      "Better time management and productivity",
      "Stronger leadership qualities",
      "Increased motivation and self-discipline",
      "Better conflict resolution skills",
      "Improved decision-making abilities",
      "Greater career advancement opportunities",
    ],
    curriculum: [
      "Understanding soft skills and their importance",
      "Emotional intelligence and self-awareness",
      "Effective communication and listening",
      "Teamwork and collaboration strategies",
      "Leadership and influence skills",
      "Conflict resolution and negotiation",
      "Time management and productivity",
      "Problem-solving and critical thinking",
      "Motivation and goal-setting techniques",
      "Stress management and resilience",
    ],
    targetAudience:
      "This course is designed for students, job seekers, and professionals at all levels who want to enhance their interpersonal skills and personal effectiveness. Whether you're starting your career or looking to advance, these soft skills are essential for success.",
  },
  "iq-development": {
    title: "IQ Development",
    subtitle: "Enhance cognitive abilities and analytical thinking skills",
    icon: "🧠",
    image: "/brain-training-cognitive-development.jpg",
    overview:
      "Unlock your intellectual potential with our IQ Development program. This course focuses on enhancing cognitive abilities, logical reasoning, and analytical thinking. Through scientifically-designed exercises and puzzles, you'll improve memory, concentration, problem-solving skills, and overall mental agility. Perfect for students preparing for competitive exams or anyone looking to boost their intellectual capabilities.",
    benefits: [
      "Improved logical reasoning and analysis",
      "Enhanced memory and concentration",
      "Better problem-solving abilities",
      "Increased mental agility and flexibility",
      "Improved performance in competitive exams",
      "Better decision-making skills",
      "Enhanced creativity and innovation",
      "Measurable improvement in IQ scores",
    ],
    curriculum: [
      "Understanding intelligence and cognitive abilities",
      "Logical reasoning and pattern recognition",
      "Numerical ability and mathematical thinking",
      "Verbal reasoning and language skills",
      "Spatial reasoning and visualization",
      "Memory enhancement techniques",
      "Concentration and focus improvement",
      "Problem-solving strategies",
      "Puzzle solving and brain teasers",
      "Competitive exam preparation",
    ],
    targetAudience:
      "This program is ideal for students preparing for competitive exams like UPSC, SSC, banking exams, and entrance tests. It's also beneficial for professionals looking to enhance their cognitive abilities and mental performance.",
  },
  tuition: {
    title: "Tuition (Class 4 to 10)",
    subtitle: "Comprehensive academic support for school students",
    icon: "📖",
    image: "/student-studying-with-tutor.jpg",
    overview:
      "Our comprehensive tuition program provides academic support for students in Classes 4 to 10. With experienced educators and personalized learning approaches, we help students master core subjects including Mathematics, Science, English, and Social Studies. Our goal is to build strong academic foundations while fostering a love for learning.",
    benefits: [
      "Improved academic performance and grades",
      "Personalized learning and attention",
      "Strong foundation in core subjects",
      "Better exam preparation and confidence",
      "Clarification of difficult concepts",
      "Development of study habits and discipline",
      "Increased interest in academics",
      "Preparation for competitive exams",
    ],
    curriculum: [
      "Mathematics: Arithmetic, Algebra, Geometry, and Problem-solving",
      "Science: Physics, Chemistry, and Biology fundamentals",
      "English: Grammar, Literature, and Communication",
      "Social Studies: History, Geography, and Civics",
      "Exam preparation and practice tests",
      "Homework assistance and doubt clearing",
      "Study skills and time management",
      "Personality development alongside academics",
    ],
    targetAudience:
      "This program is designed for students in Classes 4 to 10 who want to improve their academic performance, clarify difficult concepts, or prepare for board exams. It's suitable for students of all academic levels.",
  },
  "playschool": {
    title: "Playschool & Nursery",
    subtitle: "Nurturing early childhood development in a fun learning environment",
    icon: "🎈",
    image: "/playschool.png",
    overview:
      "Our Playchool & Nursery program is designed to provide a safe, nurturing, and stimulating environment for young children. We focus on holistic development through play-based learning, fostering creativity, social skills, and foundational knowledge. Our experienced educators create engaging activities that promote cognitive, emotional, and physical growth in a fun and supportive setting.",
    benefits: [
      "Safe and nurturing environment",
      "Play-based learning approach",
      "Focus on holistic development",
      "Experienced and caring educators",
      "Engaging activities for all areas of growth",
      "Preparation for formal schooling",
    ],
    curriculum: [
      "Play-based learning activities",
      "Creative arts and crafts",
      "Storytelling and language development",
      "Basic math and science concepts",
      "Social skills and emotional intelligence",
      "Physical activities and motor skills development",
    ],
    targetAudience:
      "This program is ideal for children aged 2 to 5 years old who are beginning their educational journey. It's designed for parents seeking a quality early childhood education that emphasizes fun, creativity, and foundational learning.",
  },
  "ssc-coaching": {
    title: "SSC Coaching",
    subtitle: "Expert preparation for SSC examinations with proven strategies",
    icon: "🚀",
    image: "/exam-preparation-study-materials.jpg",
    overview:
      "Prepare for SSC examinations with our comprehensive coaching program. Our expert instructors have years of experience helping students crack SSC exams with high scores. We cover all sections including General Awareness, Quantitative Aptitude, English Language, and Reasoning with proven strategies and extensive practice.",
    benefits: [
      "Comprehensive coverage of all SSC exam sections",
      "Expert guidance from experienced instructors",
      "Proven strategies and shortcuts",
      "Regular mock tests and performance analysis",
      "Updated study materials and resources",
      "Personalized doubt clearing sessions",
      "High success rate and proven results",
      "Career guidance and job placement support",
    ],
    curriculum: [
      "General Awareness: Current affairs and static knowledge",
      "Quantitative Aptitude: Mathematics and numerical ability",
      "English Language: Grammar, vocabulary, and comprehension",
      "Reasoning: Logical and analytical reasoning",
      "Previous year question papers and analysis",
      "Mock tests and performance evaluation",
      "Time management and exam strategies",
      "Interview preparation for selected candidates",
    ],
    targetAudience:
      "This course is designed for candidates preparing for SSC CGL, CHSL, MTS, and other SSC examinations. It's suitable for graduates and intermediate pass candidates looking for government job opportunities.",
  },
  "introduction-to-ai": {
    title: "Introduction to AI",
    subtitle: "Explore the future with artificial intelligence fundamentals",
    icon: "🤖",
    image: "/artificial-intelligence-technology-future.jpg",
    overview:
      "Step into the future with our Introduction to AI course. Learn the fundamentals of artificial intelligence, machine learning, and data science. This course is designed for beginners and covers practical applications of AI in real-world scenarios. Understand how AI is transforming industries and prepare yourself for the AI-driven future.",
    benefits: [
      "Understanding of AI and machine learning basics",
      "Knowledge of practical AI applications",
      "Introduction to programming for AI",
      "Awareness of AI career opportunities",
      "Hands-on experience with AI tools",
      "Future-ready skills for the job market",
      "Understanding of AI ethics and implications",
      "Foundation for advanced AI studies",
    ],
    curriculum: [
      "Introduction to Artificial Intelligence concepts",
      "Machine Learning fundamentals",
      "Data Science basics and analysis",
      "Python programming for AI",
      "Supervised and unsupervised learning",
      "Neural networks and deep learning introduction",
      "Natural Language Processing basics",
      "Computer vision fundamentals",
      "AI applications in various industries",
      "Ethics and future of AI",
    ],
    targetAudience:
      "This course is perfect for students, professionals, and anyone curious about artificial intelligence. No prior programming experience is required. It's ideal for those looking to understand AI trends and prepare for future career opportunities.",
  },
  "hostel-facilities": {
    title: "Hostel & Transportation Facilities",
    subtitle: "Comfortable accommodation and reliable transport services",
    icon: "🏠",
    image: "/modern-hostel-accommodation-facility.jpg",
    overview:
      "We provide comprehensive hostel and transportation facilities for students who need accommodation while pursuing their courses. Our hostels are equipped with modern amenities, secure environments, and supportive staff. We also offer reliable transportation services to ensure students can focus on their studies without worrying about logistics.",
    benefits: [
      "Safe and secure accommodation",
      "Modern amenities and facilities",
      "Supportive and friendly environment",
      "Reliable transportation services",
      "Nutritious meals and catering",
      " 24/7 security and supervision",
      "Community and peer support",
      "Convenient location near educational centers",
    ],
    curriculum: [
      "Comfortable and well-maintained rooms",
      "Common study areas and recreational facilities",
      "High-speed internet connectivity",
      "Nutritious meal plans",
      "Laundry and housekeeping services",
      "24/7 security and CCTV monitoring",
      "Regular transportation to educational centers",
      "Emergency medical support",
      "Community activities and events",
      "Counseling and support services",
    ],
    targetAudience:
      "These facilities are available for students from out of town who need accommodation while pursuing courses at SkillNest. We welcome students of all backgrounds and provide a supportive environment for their academic and personal growth.",
  },
}
